version: "3"
services:
  unix:
    build: testing/unix
    image: petitor-unix-testing
#   ports:
#      - "21:21"
#      - "22:22"
#      - "23:23"
#      - "25:25"
#      - "79:79"
#      - "80:80"
#      - "106:106"
#      - "110:110"
#      - "139:139"
#      - "143:143"
#      - "389:389"
#      - "445:445"
#      - "513:513"
#      - "636:636"
#      - "993:993"
#      - "995:995"
#      - "3306:3306"
#      - "4444:4444"
#      - "5432:5432"
#      - "5900:5900"
#      - "8009:8009"
#      - "8080:8080"
#      - "161:161/udp"
    volumes:
      - .:/opt/petitor

  petitor:
    build: .
    image: petitor
    environment:
      - DISPLAY
    volumes:
      - .:/opt/petitor
      - /tmp/.X11-unix:/tmp/.X11-unix
